# Usar la imagen base oficial de NGINX
FROM nginx:latest

# Copiar el archivo index.html al directorio predeterminado de NGINX
COPY index.html /usr/share/nginx/html/

# Exponer el puerto 80
EXPOSE 80
